### ISSUE TITLE
Cannot search with a property and attribute at once.

### ISSUE THREAD

**Issue by Megala21** [wso2/carbon-governance#299]
**Description:**
Current governance search does not support searching a property and attibute at once.

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:** 4.7.15

**OS, DB, other environment details and versions:**    N/A 

**Steps to reproduce:**
There is no way to do a search with property and attribute at once, unless the attribute is overview_name

**Related Issues:**
N/A

**Comment by cnapagoda** [comment]
Fixed with #300
